services:
  onionshare:
    image: effraie/onionshare-cli:latest
    container_name: onionshare-cli
    volumes:
      - /path/to/onionshare/files:/mnt/share
      - /path/to/onionshare/tor_data:/mnt/tor_data
    command: --website /mnt/share --persistent /mnt/tor_data/persistant-session --public
    network_mode: host
    restart: unless-stopped
networks: {}
